### ISSUE TITLE
"Federated Learning" ID's extension from "about:support" page is not "@shield.mozilla.org"

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [florian/federated-learning-addon#3]
[Affected versions]:
- Firefox 62.0b5

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a new Firefox profile with the latest version of the "Federated Learning" add-on installed.
- Have the 'extensions.legacy.enabled' pref set to 'true'.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "about:support" page.
2. Scroll down to the "Extensions" section and observe the "Federated Learning Awesome Bar" ID.

[Expected result]:
- The "Federated Learning Awesome Bar" ID ends in "@shield.mozilla.org".

[Actual result]:
- The "Federated Learning Awesome Bar" ID ends in "@mozilla.org".

[Additional Notes]:
- Attached a screenshot of the issue:

![id federated l](https://user-images.githubusercontent.com/26000308/42333809-616ecff8-8084-11e8-9f6f-620938a5083b.png)

**Comment by florian** [comment]
Thanks!
This should've been fixed by bfd6a52311396ee3d9638eec899e814f5be0466a.
